# Generated by Django 4.0.3 on 2022-10-12 20:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('author_name', models.CharField(max_length=50, null=True)),
                ('submitted', models.DateField(null=True)),
                ('image_url', models.CharField(max_length=400, null=True)),
                ('minutes', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('search_terms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('ingredients_raw_str', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('serving_size', models.CharField(max_length=50)),
                ('servings', models.IntegerField()),
                ('calories', models.DecimalField(decimal_places=1, max_digits=7, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('review_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(related_name='favorites', to='api.recipe')),
            ],
        ),
    ]
