# Generated by Django 4.0.3 on 2022-08-07 22:54

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('image_url', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('cuisine', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=100)),
                ('prep_time', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('image_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('ingredients_raw_str', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), size=None)),
                ('serving_size', models.CharField(max_length=15)),
                ('servings', models.IntegerField()),
                ('steps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=600), size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('search_terms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
                ('author_id', models.IntegerField()),
                ('author_name', models.CharField(max_length=30)),
                ('submitted', models.DateField()),
                ('image_url', models.CharField(max_length=250, null=True)),
                ('minutes', models.IntegerField()),
                ('category', models.CharField(max_length=30, null=True)),
                ('calories', models.DecimalField(decimal_places=1, max_digits=7)),
                ('n_steps', models.IntegerField()),
                ('n_ingredients', models.IntegerField()),
                ('nutrition', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=1, max_digits=7), size=None)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('review_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TryArray',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(related_name='favorites', to='api.cuisine')),
            ],
        ),
    ]
