# Generated by Django 4.0.3 on 2022-08-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipe_ingredients_raw_str'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TryArray',
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='api.recipe'),
        ),
    ]
